/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 GamerRoom.glb
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function GameRoom(props) {
  const { nodes, materials } = useGLTF('/GamerRoom.glb')
  return (
    <group scale={3.5} rotation={[0,Math.PI *1.5,0]} position={[0,-5,2]} {...props} dispose={null}>
      <mesh geometry={nodes.Cube.geometry} material={nodes.Cube.material} position={[0.52, 2.2, -0.72]} scale={3.16} />
      <mesh geometry={nodes.Cube003.geometry} material={materials['Material.002']} position={[0.49, 2.19, -0.7]} scale={[0.06, 0.01, 0.01]} />
      <mesh geometry={nodes.Cube002.geometry} material={materials['Material.005']} position={[-2.29, 0.63, -1.5]} rotation={[0, Math.PI / 2, 0]} scale={[1.43, 0.1, 0.59]} />
      <mesh geometry={nodes.Cylinder.geometry} material={materials['Material.006']} position={[-2.29, 0.45, -1.48]} rotation={[0, Math.PI / 2, 0]} scale={[0.03, 0.06, 0.03]} />
      <mesh geometry={nodes.Cube007.geometry} material={materials['Material.003']} position={[-2.36, 1.02, -1.32]} rotation={[0, -0.32, 0]} scale={[0, 0.01, 0]} />
      <mesh geometry={nodes.Cube005.geometry} material={materials['Material.004']} position={[-1.78, 0.51, -0.37]} rotation={[0, Math.PI / 2, 0]} scale={[0.32, 0.3, 0.55]} />
      <mesh geometry={nodes.Cylinder001.geometry} material={materials['Material.007']} position={[-2.68, 1.27, -1.57]} rotation={[0, Math.PI / 2, 0]} scale={[0.2, 0.02, 0.2]} />
      <mesh geometry={nodes.Cube008.geometry} material={materials['Material.039']} position={[-2.63, 1.35, -1.57]} rotation={[-Math.PI / 2, 1.45, Math.PI / 2]} scale={[0.36, 0.2, 0.02]} />
      <mesh geometry={nodes.Cylinder002.geometry} material={materials['Material.007']} position={[-2.61, 1.27, -0.92]} rotation={[-Math.PI, 1.16, -Math.PI]} scale={[0.2, 0.02, 0.2]} />
      <mesh geometry={nodes.Cube006.geometry} material={nodes.Cube006.material} position={[-2.57, 1.35, -0.94]} rotation={[-2.86, 1.15, 2.88]} scale={[0.36, 0.2, 0.02]} />
      <mesh geometry={nodes.Cube009.geometry} material={materials['Material.009']} position={[-2.46, 1.21, -2.38]} rotation={[0, Math.PI / 2, 0]} scale={[0.07, 0.19, 0.19]} />
      <mesh geometry={nodes.Cube010.geometry} material={materials['Material.008']} position={[-2.27, 1.21, -2.38]} rotation={[0, Math.PI / 2, 0]} scale={[0.07, 0.19, 0.19]} />
      <mesh geometry={nodes.Cube012.geometry} material={materials['Material.010']} position={[-2.27, 1.21, -2.38]} rotation={[0, Math.PI / 2, 0]} scale={[0.07, 0.19, 0.19]} />
      <mesh geometry={nodes.Cube011.geometry} material={materials['Material.018']} position={[-1.78, 0.98, 3.16]} scale={3.16} />
      <mesh geometry={nodes.Sphere.geometry} material={materials['Material.017']} position={[-2.5, 0.95, 3.15]} scale={0.04} />
      <mesh geometry={nodes.Cube013.geometry} material={nodes.Cube013.material} position={[-3.13, 3.41, -3.28]} scale={[0.05, 0.52, 0.52]} />
      <mesh geometry={nodes.Cube014.geometry} material={materials['Material.028']} position={[-3.16, 3.41, -3.28]} scale={[0.05, 0.52, 0.52]} />
      <mesh geometry={nodes.Cube015.geometry} material={nodes.Cube015.material} position={[-3.13, 3.93, -2.96]} scale={[0.07, 0.04, 0.03]} />
      <mesh geometry={nodes.Cube016.geometry} material={nodes.Cube016.material} position={[-3.13, 3.93, -3.59]} scale={[0.07, 0.04, 0.03]} />
      <mesh geometry={nodes.Cube020.geometry} material={materials['Material.022']} position={[1.66, 0.52, 2.57]} scale={[0.39, 0.51, 0.42]} />
      <mesh geometry={nodes.Cube019.geometry} material={materials['Material.031']} position={[2.61, 0.36, -3.37]} scale={[1.23, 0.07, 0.84]} />
      <mesh geometry={nodes.Cube023.geometry} material={materials['Material.029']} position={[-1.78, 1.03, 3.15]} rotation={[0, 0, -Math.PI / 2]} scale={[0.51, 0.04, 0.01]} />
      <mesh geometry={nodes.Cube024.geometry} material={materials['Material.020']} position={[1.98, 0.51, -3.37]} scale={[0.62, 0.08, 0.84]} />
      <mesh geometry={nodes.Cube025.geometry} material={materials['Material.021']} position={[3.21, 0.51, -3.37]} scale={[0.6, 0.08, 0.84]} />
      <mesh geometry={nodes.Cube026.geometry} material={materials['Material.016']} position={[2.59, 0.16, -3.37]} scale={[1.23, 0.07, 0.84]} />
      <mesh geometry={nodes.Cube027.geometry} material={materials['Material.034']} position={[3.85, 0.54, -3.37]} scale={[1.23, 0.05, 0.84]} />
      <mesh geometry={nodes.Cube029.geometry} material={materials['Material.023']} position={[1.64, 0.29, 1]} scale={[0.57, 0.17, 0.31]} />
      <mesh geometry={nodes.Cube030.geometry} material={nodes.Cube030.material} position={[1.64, 0.05, 1]} scale={[0.66, 0.02, 0.36]} />
      <mesh geometry={nodes.Cube031.geometry} material={materials['Material.025']} position={[1.64, 0.05, 1.33]} scale={[0.66, 0.02, 0.36]} />
      <mesh geometry={nodes.Cube033.geometry} material={materials['Material.024']} position={[1.64, 0.05, 0.66]} scale={[0.66, 0.02, 0.36]} />
      <mesh geometry={nodes.Cube021.geometry} material={materials['Material.003']} position={[-2.36, 1.02, -1.32]} rotation={[0, -0.32, 0]} scale={[0, 0.01, 0]} />
      <mesh geometry={nodes.Cube032.geometry} material={materials['Material.033']} position={[-0.67, 0.77, -1.33]} rotation={[0, 0.49, 0]} scale={[0.05, 0.02, 0.29]} />
      <mesh geometry={nodes.Cube022.geometry} material={materials['Material.036']} position={[1.72, -0.06, -0.94]} scale={[1.65, 0.38, -0.01]} />
      <mesh geometry={nodes.Cube036.geometry} material={materials['Material.032']} position={[3.85, 0.57, -3.37]} scale={[1.23, 0.07, 0.84]} />
      <mesh geometry={nodes.Cube041.geometry} material={materials['Material.035']} position={[-3.16, 3.78, -0.47]} scale={[0, 0.09, 0.09]} />
      <mesh geometry={nodes.Cube037.geometry} material={materials['Material.035']} position={[-3.16, 3.78, -1.25]} scale={[0, 0.09, 0.09]} />
      <mesh geometry={nodes.Cube038.geometry} material={materials['Material.035']} position={[-3.16, 3.78, 0.35]} scale={[0, 0.09, 0.09]} />
      <mesh geometry={nodes.Cube017.geometry} material={materials['Material.037']} position={[0.52, 2.2, -0.72]} scale={3.16} />
      {/* <mesh geometry={nodes.Plane.geometry} material={materials['Material.038']} position={[-41.48, -1.52, 17.7]} scale={72.08} /> */}
      <group position={[-2.08, 1.04, -1.14]} rotation={[0, Math.PI / 2, 0]} scale={[0.36, 0.2, 0.13]}>
        <mesh geometry={nodes.Plane001.geometry} material={materials['Material.225']} />
        <mesh geometry={nodes.Plane001_1.geometry} material={materials['Material.195']} />
        <mesh geometry={nodes.Plane001_2.geometry} material={materials['Material.044']} />
        <mesh geometry={nodes.Plane001_3.geometry} material={materials['Material.194']} />
        <mesh geometry={nodes.Plane001_4.geometry} material={materials['Material.043']} />
        <mesh geometry={nodes.Plane001_5.geometry} material={materials['Material.080']} />
        <mesh geometry={nodes.Plane001_6.geometry} material={materials['Material.040']} />
        <mesh geometry={nodes.Plane001_7.geometry} material={materials['Material.011']} />
        <mesh geometry={nodes.Plane001_8.geometry} material={materials['Material.110']} />
        <mesh geometry={nodes.Plane001_9.geometry} material={materials['Material.111']} />
        <mesh geometry={nodes.Plane001_10.geometry} material={materials['Material.196']} />
        <mesh geometry={nodes.Plane001_11.geometry} material={materials['Material.220']} />
        <mesh geometry={nodes.Plane001_12.geometry} material={materials['Material.078']} />
        <mesh geometry={nodes.Plane001_13.geometry} material={materials['Material.222']} />
        <mesh geometry={nodes.Plane001_14.geometry} material={materials['Material.223']} />
        <mesh geometry={nodes.Plane001_15.geometry} material={materials['Material.224']} />
      </group>
      <group position={[-2.05, 1.05, -1.76]} rotation={[-1.5, 1.54, 1.5]} scale={0.03}>
        <mesh geometry={nodes.Plane002.geometry} material={materials['Material.015']} />
        <mesh geometry={nodes.Plane002_1.geometry} material={materials['Material.014']} />
        <mesh geometry={nodes.Plane002_2.geometry} material={materials['Material.013']} />
        <mesh geometry={nodes.Plane002_3.geometry} material={materials['Material.012']} />
      </group>
    </group>
  )
}

useGLTF.preload('/GamerRoom.glb')
