/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 RedRoom.gltf
Author: LaisLH (https://sketchfab.com/JanusC)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/red-room-19e54b00169f486590a4f3d2d04f396b
Title: Red Room
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function RedRoom(props) {
  const { nodes, materials } = useGLTF('/RedRoom.gltf')
  return (
    <group position={[0,-5,3]} rotation={[0,Math.PI * 1,0]} scale={5} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={0.01}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.Quarto_Floor_0.geometry} material={materials.Floor} />
            <mesh geometry={nodes.Quarto_Light_0.geometry} material={materials.Light} />
            <mesh geometry={nodes.Quarto_Wall_0.geometry} material={materials.Wall} />
          </group>
          <group position={[-297.04, 0.44, 50.38]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.Door_Floor_0.geometry} material={materials.Floor} />
            <mesh geometry={nodes.Door_DoorMetal_0.geometry} material={materials.DoorMetal} />
          </group>
          <group position={[-5.05, 0.42, 221.09]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <group position={[-0.36, 0.19, 0.8]}>
              <mesh geometry={nodes.DrawerRight_Table_0.geometry} material={materials.Table} />
              <mesh geometry={nodes.DrawerRight_Table2_0.geometry} material={materials.Table2} />
            </group>
            <group position={[0.38, 0.2, 0.8]}>
              <mesh geometry={nodes.DrawerLeft_Table_0.geometry} material={materials.Table} />
              <mesh geometry={nodes.DrawerLeft_Table2_0.geometry} material={materials.Table2} />
            </group>
            <mesh geometry={nodes.Table001_Table_0.geometry} material={materials.Table} />
            <mesh geometry={nodes.Table001_Table2_0.geometry} material={materials.Table2} />
          </group>
          <group position={[-396.74, 0.44, 150.12]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={[45, 2.5, 100]}>
            <mesh geometry={nodes.Door002_Floor_0.geometry} material={materials.Floor} />
            <mesh geometry={nodes.Door002_DoorMetal_0.geometry} material={materials.DoorMetal} />
          </group>
          <group position={[-107, 0.42, 216.24]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.Abajour_Abajour1_0.geometry} material={materials.Abajour1} />
            <mesh geometry={nodes.Abajour_Abadour2_0.geometry} material={materials.Abadour2} />
          </group>
          <group position={[-3.16, 136.04, 249.67]} scale={100}>
            {/* <mesh geometry={nodes.TV_TV_0.geometry} material={materials.material_14} />
            <mesh geometry={nodes.TV_TV_Screen_0.geometry} material={materials.TV_Screen} />
            <mesh geometry={nodes.TV_LightTV_0.geometry} material={materials.LightTV} /> */}
          </group>
          <group position={[-84.73, 238.1, 39.32]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.Circle_LightRedCircle_0.geometry} material={materials.LightRedCircle} />
            <mesh geometry={nodes.Circle_LightRedCircle2_0.geometry} material={materials.LightRedCircle2} />
          </group>
          <group position={[62.31, 238.1, 131.51]} rotation={[-Math.PI / 2, 0, 0]} scale={77.06}>
            <mesh geometry={nodes.Circle001_LightRedCircle_0.geometry} material={materials.LightRedCircle} />
            <mesh geometry={nodes.Circle001_LightRedCircle2_0.geometry} material={materials.LightRedCircle2} />
          </group>
          <group position={[54.15, 238.1, -100.01]} rotation={[-Math.PI / 2, 0, 0]} scale={97.68}>
            <mesh geometry={nodes.Circle002_LightRedCircle_0.geometry} material={materials.LightRedCircle} />
            <mesh geometry={nodes.Circle002_LightRedCircle2_0.geometry} material={materials.LightRedCircle2} />
          </group>
          {/* <mesh geometry={nodes.Bed_Bed_0.geometry} material={materials.material} position={[23.69, 0, -112.9]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={100} /> */}
          <mesh geometry={nodes.Chair_Chair_0.geometry} material={materials.Chair} position={[120.18, 0.44, 157.51]} rotation={[-Math.PI / 2, 0, 0.58]} scale={100} />
          <mesh geometry={nodes.Cortina_Low_Poly_Cortina_0.geometry} material={materials.Cortina} position={[194.29, 0.42, -3.1]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} scale={100} />
          <mesh geometry={nodes.Rug_Rug_0.geometry} material={materials.material_3} position={[82.55, 0.44, 115.56]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes.DoorFrame_Floor_0.geometry} material={materials.Floor} position={[-297.04, 0.44, 56.31]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes.Door003_Floor_0.geometry} material={materials.Floor} position={[-390.81, 0.44, 150.12]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={[45, 2.5, 100]} />
          {/* <mesh geometry={nodes.Travesseiro001_Travesseiro_0.geometry} material={materials.Travesseiro} position={[4.92, 67.79, -168.36]} rotation={[-2.82, 0, 0]} scale={100} />
          <mesh geometry={nodes.Travesseiro002_Travesseiro_0.geometry} material={materials.Travesseiro} position={[61.71, 67.79, -168.36]} rotation={[-2.75, 0.61, -0.24]} scale={100} />
          <mesh geometry={nodes.Travesseiro003_Travesseiro_0.geometry} material={materials.Travesseiro} position={[35.06, 72.48, -146.24]} rotation={[-2.31, 0, 0]} scale={100} />
          <mesh geometry={nodes.Travesseiro004_Travesseiro_0.geometry} material={materials.Travesseiro} position={[-27.29, 67.79, -145.37]} rotation={[-2.76, 0.57, -0.22]} scale={100} /> */}
          <mesh geometry={nodes.Quadro_Material003_0.geometry} material={materials['Material.003']} position={[200, 144.75, 151.66]} rotation={[-Math.PI / 2, -Math.PI / 2, 0]} scale={100} />
          <mesh geometry={nodes.Cortina_Low_Poly001_Cortina_0.geometry} material={materials.Cortina} position={[-60.13, 0, -138.16]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/RedRoom.gltf')
