/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 WhiteRoom.gltf
Author: dylanheyes (https://sketchfab.com/dylanheyes)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/minimalistic-modern-bedroom-4f3db3cb57bd4bce886f7b9a13273a2f
Title: Minimalistic Modern Bedroom
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function WhiteRoom(props) {
  const { nodes, materials } = useGLTF('/WhiteRoom.gltf')
  return (
    <group scale={4} position={[0,3,-4]} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={0.09}>
        <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={[2721.36, 3174.92, 1814.24]}>
            <mesh geometry={nodes.Bedroom_Bedroom_0.geometry} material={materials.Bedroom} />
            <mesh geometry={nodes.Bedroom_Bedroom_0_1.geometry} material={materials.Bedroom} />
            <mesh geometry={nodes.Bedroom_Duvet_0.geometry} material={materials.Duvet} />
            <mesh geometry={nodes.Bedroom_Carpet_0.geometry} material={materials.Carpet} />
            <mesh geometry={nodes.Bedroom_Windows_0.geometry} material={materials.Windows} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/WhiteRoom.gltf')
